import bcrypt from "bcryptjs";
import { getClient, getDbKind, initDb } from "./pool.js";
import { getDialect } from "./dialect/index.js";
import { formatSubmissionPublicId, schoolYearForDate } from "./schema.js";
import { env } from "../config/env.js";

/**
 * Seed data:
 *  - A default school
 *  - An admin user (from env or fallback)
 *  - The reference "CDM" form (from the plan) with its fields
 *  - The reference submission (Johnny Smith, Submission ID from the plan)
 *
 * Runs on either database mode. The original version leaned on multi-statement
 * T-SQL (`IF NOT EXISTS (...) INSERT ...; SELECT ...`), which has no SQLite
 * equivalent (libSQL executes one statement per call), so every guard is now an
 * explicit read-then-write — which behaves identically on SQL Server.
 */
async function seed() {
  await initDb();
  const db = getClient();
  const dialect = () => getDialect(getDbKind());

  // 0. Resolve the Academics organization (the tenant that owns all seeded data).
  //    initDb() guarantees the two default orgs exist (see the DDL seed block).
  const orgRows = await db.query<{ id: number }>(
    `SELECT id FROM dbo.organizations WHERE slug = @slug`,
    { slug: "academics" }
  );
  const orgId = orgRows[0].id;

  // 1. Default school
  let school = (
    await db.query<{ id: number; name: string }>(
      `SELECT id, name FROM dbo.schools WHERE name = @name`,
      { name: "Sample School" }
    )
  )[0];
  if (!school) {
    school = (
      await db.query<{ id: number; name: string }>(
        dialect().insertReturning({
          table: "schools",
          columns: ["name", "district"],
          returning: ["id", "name"],
          values: "@name, @district",
        }),
        { name: "Sample School", district: "Sample District" }
      )
    )[0];
  }

  // 2. Default admin (belongs to Academics org)
  const adminEmail = env.webhookAdminEmail || "admin@schoolforms.local";
  const adminPassword = env.webhookAdminPassword || "ChangeMe123!";
  const existingAdmin = await db.query<{ id: number }>(
    `SELECT id FROM dbo.users WHERE email = @email`,
    { email: adminEmail }
  );
  if (!existingAdmin.length) {
    const adminHash = await bcrypt.hash(adminPassword, 12);
    await db.query(
      dialect().insertReturning({
        table: "users",
        columns: ["email", "password_hash", "role", "school_id", "display_name", "organization_id"],
        returning: ["id"],
        values: "@email, @hash, 'admin', @id, @displayName, @orgId",
      }),
      {
        email: adminEmail,
        hash: adminHash,
        id: school.id,
        displayName: "System Admin",
        orgId,
      }
    );
  }

  // 3. CDM form
  // NOTE: `id` is generated by the database, so the row is inserted and read back
  // in one statement, then that id is used for the fields + reference submission.
  let form = (
    await db.query<{ id: number; code: string | null }>(
      `SELECT id, code FROM dbo.forms WHERE title = @title`,
      { title: "CDM" }
    )
  )[0];
  if (!form) {
    form = (
      await db.query<{ id: number; code: string | null }>(
        dialect().insertReturning({
          table: "forms",
          columns: [
            "title",
            "description",
            "school_id",
            "designer_id",
            "organization_id",
            "status",
            "code",
            "submission_seq",
          ],
          returning: ["id", "code"],
          values: "@title, @description, @schoolId, NULL, @orgId, 'published', 'CDM', 0",
        }),
        {
          title: "CDM",
          description: "Child Development Monitor form (reference)",
          schoolId: school.id,
          orgId,
        }
      )
    )[0];
  }
  const FORM_ID = form.id;

  // 4. CDM fields (order matters; staff_only on "All others")
  const fields = [
    { label: "Student Name", type: "text", required: true, staff_only: false, sort_order: 0 },
    { label: "Student ID", type: "text", required: true, staff_only: false, sort_order: 1 },
    { label: "Grade", type: "select", required: true, staff_only: false, options: ["K", "1", "2", "3", "4", "5"], sort_order: 2 },
    { label: "Does the student attend school regularly?", type: "radio", required: true, staff_only: false, options: ["Yes", "No"], sort_order: 3 },
    { label: "Is there a concern with attendance?", type: "radio", required: true, staff_only: false, options: ["Yes", "No"], sort_order: 4 },
    { label: "Is the student progressing academically?", type: "radio", required: true, staff_only: false, options: ["Yes", "No"], sort_order: 5 },
    { label: "Behavioral concerns?", type: "radio", required: true, staff_only: false, options: ["Yes", "No"], sort_order: 6 },
    { label: "Notes", type: "textarea", required: false, staff_only: true, sort_order: 7 },
  ];
  const existingFieldLabels = new Set(
    (
      await db.query<{ label: string }>(
        `SELECT label FROM dbo.form_fields WHERE form_id = @formId`,
        { formId: FORM_ID }
      )
    ).map((r) => r.label)
  );
  for (const f of fields) {
    if (existingFieldLabels.has(f.label)) continue;
    await db.query(
      `INSERT INTO dbo.form_fields (form_id, label, type, options, required, staff_only, sort_order, placeholder)
       VALUES (@formId, @label, @type, @options, @required, @staffOnly, @sortOrder, NULL)`,
      {
        formId: FORM_ID,
        label: f.label,
        type: f.type,
        options: f.options ? JSON.stringify(f.options) : null,
        required: f.required,
        staffOnly: f.staff_only,
        sortOrder: f.sort_order,
      }
    );
  }

  // 5. Reference submission (from plan) — Johnny Smith
  // The reference row uses the new incremental id format `CDM-00001`, with the
  // numeric portion stored in submission_seq so the per-form counter continues
  // from the correct value for subsequent (real) submissions.
  const PUBLIC_ID = "CDM-00001";
  const submissionExists = await db.query<{ id: number }>(
    `SELECT id FROM dbo.submissions WHERE public_id = @publicId`,
    { publicId: PUBLIC_ID }
  );
  if (!submissionExists.length) {
    const schoolYear = schoolYearForDate(new Date());
    const sub = await db.query<{ id: number }>(
      dialect().insertReturning({
        table: "submissions",
        columns: [
          "public_id",
          "form_id",
          "school_id",
          "organization_id",
          "status",
          "submission_seq",
          "school_year",
        ],
        returning: ["id"],
        values: "@publicId, @formId, @schoolId, @orgId, 'submitted', 1, @schoolYear",
      }),
      { publicId: PUBLIC_ID, formId: FORM_ID, schoolId: school.id, orgId, schoolYear }
    );
    const submissionId = sub[0].id;
    // Ensure the form counter accounts for the seeded reference submission so the
    // next real submission for this form allocates `CDM-00002`.
    await db.query(
      `UPDATE dbo.forms SET submission_seq = submission_seq + 1 WHERE id = @formId AND submission_seq < 1`,
      { formId: FORM_ID }
    );

    // Map field labels to their ids
    const fieldRows = await db.query<{ id: number; label: string }>(
      `SELECT id, label FROM dbo.form_fields WHERE form_id = @formId`,
      { formId: FORM_ID }
    );
    const fieldIdByLabel = new Map(fieldRows.map((r) => [r.label, r.id]));

    const answers = [
      { label: "Student Name", value: "Johnny Smith" },
      { label: "Student ID", value: "12345" },
      { label: "Grade", value: "3" },
      { label: "Does the student attend school regularly?", value: "No" },
      { label: "Is there a concern with attendance?", value: "Yes" },
      { label: "Is the student progressing academically?", value: "No" },
      { label: "Behavioral concerns?", value: "No" },
    ];
    for (const a of answers) {
      const fieldId = fieldIdByLabel.get(a.label);
      if (fieldId) {
        await db.query(
          `INSERT INTO dbo.submission_values (submission_id, field_id, value)
           VALUES (@subId, @fieldId, @value)`,
          { subId: submissionId, fieldId, value: a.value }
        );
      }
    }
  }

  // eslint-disable-next-line no-console
  console.log(
    `[seed] Done. Admin: ${adminEmail} (${adminPassword}). CDM form seeded (code=CDM). ` +
      `Reference submission ${PUBLIC_ID} present.`
  );
  await db.close();
}

seed().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("[seed] failed:", err);
  process.exit(1);
});
